
import java.io.File;
import static java.lang.Thread.sleep;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author paco
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        jTextField1.grabFocus();
        jLabel2.setIcon(new ImageIcon(getClass().getResource("E00.gif")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de la pelota animado");
        setPreferredSize(new java.awt.Dimension(750, 500));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Cadena:");

        jLabel4.setText("Estado:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estado", "Letra", "Salidad"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 51, 0));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));
        jComboBox1.setBorder(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("----->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("<------");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jMenu3.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar3.add(jMenu3);

        jMenu4.setText("Salir");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Acerca de");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenuBar3.add(jMenu5);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 307, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ok() {
        String salida = "", cadena2 = jTextField1.getText().toUpperCase();
        long has;
        char cadena = 0;
        int estados = 0, estado = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        char are[] = new char[cadena2.length()];
        for (int i = 0; i < cadena2.length(); i++) {
            are[i] = cadena2.charAt(i);
        }
        vaciarJtable(jTable1);
        for (int i = 0; i < are.length; i++) {
            cadena = are[i];
            if (estado == 0 && cadena == 'A') {
                salida = "C";
                estado = 4;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E0A.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 0 && cadena == 'B') {
                salida = "C";
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E0B.gif")));

                estado = 3;
                lee(estado, cadena + "", salida);

                System.out.println("Estado: " + estado + " Salidad: " + salida);
//                break;
            } else if (estado == 1 && cadena == 'A') {
                salida = "C";

                estado = 5;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E1A.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);
//                break;
            } else if (estado == 1 && cadena == 'B') {
                salida = "D";
                estado = 2;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E1B.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 2 && cadena == 'A') {
                salida = "C";
//                break;
                estado = 6;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E2A.gif")));
                System.out.println("Estado: " + estado + " Salidad: " + salida);

            } else if (estado == 2 && cadena == 'B') {
                salida = "D";
                estado = 0;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E2B.gif")));
                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 3 && cadena == 'A') {
                salida = "C";
                estado = 7;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E3A.gif")));
                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 3 && cadena == 'B') {
                salida = "D";
                estado = 1;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E3B.gif")));
                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 4 && cadena == 'A') {
                salida = "C";
                estado = 1;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E4A.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 4 && cadena == 'B') {
                salida = "C";
                estado = 7;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E4B.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);
//                break;

            } else if (estado == 5 && cadena == 'A') {
                salida = "D";
                estado = 0;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E5A.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 5 && cadena == 'B') {
                salida = "D";
                estado = 6;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E5B.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 6 && cadena == 'A') {
                salida = "C";
                estado = 3;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E6A.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 6 && cadena == 'B') {
                salida = "D";
                estado = 4;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E6B.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 7 && cadena == 'A') {
                salida = "D";
                estado = 2;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E7A.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            } else if (estado == 7 && cadena == 'B') {
                salida = "D";
                estado = 5;
                lee(estado, cadena + "", salida);
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E7B.gif")));

                System.out.println("Estado: " + estado + " Salidad: " + salida);

//                break;
            }

        }

        System.out.println("la  final : Estado: " + estado + " Salidad: " + salida);
        jTextField1.setText("");

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String texto = "";

        String patron = "(A|B|0)+";
        Pattern pattern = Pattern.compile(patron);
        if (!jTextField1.getText().equals("")) {
            texto = jTextField1.getText().toUpperCase();
        } else {
            System.out.println("metete algo");
                            jLabel2.setIcon(new ImageIcon(getClass().getResource("E00.gif")));

        }
        Matcher matcher = pattern.matcher(texto);
        if (matcher.matches()) {
            System.out.println("si esta");
//            JOptionPane.showMessageDialog(null, "SI CUMPLE", "SALIDAD", JOptionPane.INFORMATION_MESSAGE);

            ok();
//            animales p = new animales("jose", 250, jLabel2);
//            p.start();
        } else {
            System.out.println("no esta");
            JOptionPane.showMessageDialog(null, "NO CUMPLE", "SALIDAD", JOptionPane.ERROR_MESSAGE);
//            jLabel2.setIcon(new ImageIcon(getClass().getResource("normal.gif")));
                jLabel2.setIcon(new ImageIcon(getClass().getResource("E00.gif")));

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        vaciarJtable(jTable3);
        if (selecArchivo.showDialog(null, "Seleccionar archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = selecArchivo.getSelectedFile();
            if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                //  JOptionPane.showMessageDialog(null, modeloE.Importar(archivo, jTable1) + "\n Formato ." + archivo.getName().substring(archivo.getName().lastIndexOf(".") + 1));
                modeloE.Importar(archivo, jTable3);
            } else {
                JOptionPane.showMessageDialog(null, "Elija un formato valido.");
            }
        }  
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
int conta=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
           try{
            jTextField1.setText("" + modeloE.ret(conta));
            conta++;
        }catch(Exception e){

        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           try{
            jTextField1.setText("" + modeloE.ret(conta));
            conta--;
        }catch(Exception e){

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Juego de la Pelota Automatas,\nAlumnos:\nFrancisco Arcos Jaimes No.Control 13520541 \nOscar Daniel Muñoz Abarca (El malito) No.Control 13520506");
        
    }//GEN-LAST:event_jMenu5MousePressed

    JFileChooser selecArchivo = new JFileChooser();
    File archivo;
    ModeloExcel modeloE = new ModeloExcel();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    public void vaciarJtable(JTable fila) {
        DefaultTableModel modelo = (DefaultTableModel) fila.getModel();
        modelo.setRowCount(0);
    }

    public void anadirAJTable(JTable jt, Object[] arr) {
        DefaultTableModel modelo = (DefaultTableModel) jt.getModel();//saco el modelo o estrcutura de datos de la tabla
        modelo.addRow(arr);//añado la fila de datos a la estructura de la tabla, y ya aparecerá en la tabla grafica.
    }//fin de metodo

    public void lee(int E, String X1, String X2) {

        Object[] nuevaFila = {E, X1, X2};//se crea un arreglo unidimensional con los datos obtenidos, esta será la fila de datos que se agregara ala tabla de visualizar registros.
        anadirAJTable(jTable1, nuevaFila);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
